---
title: "Class 3 Homework"
format: 
  html:
    embed-resources: true
---

```{r}
#| warning: false
library(tidyverse)     # loads the tidyverse tools
library(RPostgres)     # loads the database driver for PostgreSQL
library(connections)   # helps RPostgres work with RStudio
library(keyring)       # access to a local encrypted keychain for passwords

con <- connection_open(RPostgres::Postgres(),
          dbname = "syntheticmguh",
          host = "34.145.215.95",
          user = "hids502_student",
          password = key_get(service = "syntheticmguh", 
                             username = "hids502_student"),
          # Tell the driver to return very large integers as floating point (vs truncating them)
          bigint = "numeric")
        
```

# Question 1

What are the top three causes of morbidity (illness)? This does not need to be a per patient query because a patient can have multiple illnesses. The following provides the 3 most prevalent illnesses in the dataset. They appear to all be related to respiratory infections.

```{sql connection=con}
SELECT COUNT(*) AS condition_count, code, description
FROM conditions
WHERE description LIKE '%(disorder)%'
GROUP BY code, description
ORDER BY condition_count DESC
LIMIT 3;
```

We can include more than respiratory infections as well. It appears that upper respiratory infections, hypertension, and anemia are three of the top illnesses in the dataset.

```{sql connection=con}
SELECT COUNT(*) AS condition_count, code, description
FROM conditions
WHERE description LIKE '%(disorder)%'
GROUP BY code, description
ORDER BY condition_count DESC
LIMIT 10;
```

What are the top three causes of mortality? It appears that they are end-stage renal disease, heart attack / heart failure, and COVID-19.

```{sql connection=con}
SELECT COUNT(*) AS death_count, encounters.reasondescription
FROM observations
INNER JOIN encounters
ON observations.encounter = encounters.id
WHERE observations.code = '69453-9'
GROUP BY encounters.reasondescription
ORDER BY death_count DESC
```

# Question 2

What is the breakdown of spending between Medicaid, Medicare, and everything else? I first produced a table representing the breakdown of spending among all payers.

```{sql connection=con}
SELECT SUM(total_claim_cost), payers.name
FROM encounters
INNER JOIN payers
ON encounters.payer = payers.id
GROUP BY name;
```
I then produced a table that represented the breakdown of spending among Medicare, Medicaid, and everything else. Everything else is the sum of the total cost for the payers besides Medicare and Medicaid. 
```{sql connection=con}
SELECT 
  SUM(encounters.total_claim_cost) AS total_cost,
  CASE WHEN payers.name = 'Medicare' THEN 'Medicare'
       WHEN payers.name = 'Medicaid' THEN 'Medicaid'
       ELSE 'Everything else'END AS payer_group
FROM payers
INNER JOIN encounters
ON encounters.payer = payers.id
GROUP BY payer_group
ORDER BY total_cost DESC;
```