---
title: "COVID Registry Skeleton"
format: 
  html:
    embed-resources: true
---

```{r}
#| warning: false
library(tidyverse)     # loads the tidyverse tools
library(RPostgres)     # loads the database driver for PostgreSQL
library(connections)   # helps RPostgres work with RStudio
library(keyring)       # access to a local encrypted keychain for passwords

con <- connection_open(RPostgres::Postgres(),
          dbname = "syntheticmguh",
          host = "34.145.215.95",
          user = "hids502_student",
          password = key_get(service = "syntheticmguh", 
                             username = "hids502_student"),
          # Tell the driver to return very large integers as floating point (vs truncating them)
          bigint = "numeric")

```

# COVID Data

How many encounters for COVID? Here we are going to use a fuzzy match using SQL, ie the "%" sign and the LIKE
```{sql connection=con}
-- results, observations
SELECT patient, description, code, start, stop
FROM encounters
WHERE reasondescription like '%COVID%'

```

```{sql connection=con}
-- results, observations
SELECT DISTINCT
FROM encounters
WHERE reasondescription like '%COVID%'

```
Why kind of encounters are these?

```{sql connection=con}
SELECT encounterclass, description, count(*) 
FROM encounters 
WHERE reasondescription like '%COVID%' 
GROUP BY encounterclass, description
```

Where what about lab tests? These show in the `observations` tables. How may tests did we have, what proportion were positive? You will want to start by looking at the table structure, then figuring out how you might be able to find a value. Remember, these disease is COVID-19, but the virus is SARS-CoV-2!

So both suspected covid and covid for one LOINC code. 

```{sql connection=con}
SELECT DISTINCT encounters.patient, encounters.reasondescription, observations.value
FROM encounters
JOIN observations
ON observations.encounter = encounters.id
WHERE observations.description LIKE '%SARS-CoV-2%'
  AND observations.value IS NULL
  AND encounters.reasondescription = 'Suspected COVID-19';

```
How about people who are recorded as having COVID as a problem/condition? What kinds of problem/conditions do we have? How many patients were suspected to have COVID in 2020?

```{sql connection=con}
SELECT COUNT(DISTINCT(encounters.patient)), reasondescription
FROM encounters
INNER JOIN observations
ON observations.encounter = encounters.id
WHERE observations.description like '%SARS-CoV-2%'
GROUP BY reasondescription
```

## Creating A COVID Registry

Create a "registry" of the outpatients diagnosed with COVID (by any manner). Create your "registry" as a CTE and then show that you can query against it to provide summary metrics, eg total numbers etc.

You may want to use either a `UNION` clause, or construct a join using the `WHERE id IN (SELECT id FROM ...)` syntax which returns a single row per match regardless of the number of matching rows on the right.


```{sql connection=con}
with anemic_population as (
  -- Select everyone that *currently* has diabetes
  select distinct conditions.start, patients.*
  from patients
  join conditions on conditions.patient = patients.id
    and description like 'Anemia%' 
)
-- Now use that big 'view' to get just the count of patients
select count(*) from anemic_population 
```

